### ISSUE TITLE
Automatically push to PyPI

### ISSUE THREAD

**Issue by marcenacp** [mlcommons/croissant#112]
- PyPI: `mlcroissant`
- Rename `ml_croissant` -> `mlcroissant`
- Github actions

**Comment by parth656** [comment]
@marcenacp pls assign it to me

**Comment by parth656** [comment]
@lunixbochs @marcenacp @jim80net @bollacker pls assign it to me

**Comment by marcenacp** [comment]
@parth656, great. Thanks a lot for taking care of this!

The admin contact on ML Commons side to set up PyPI credentials and environment variables on GitHub is admin@mlcommons.org.

Thanks a lot!

**Comment by marcenacp** [comment]
@parth656 We're going to need this feature soon in order to integrate Croissant with TFDS. When do you plan to work on it? Thanks!

**Comment by nssalian** [comment]
@marcenacp, I thought of picking up a first issue and saw this. But, I think https://github.com/mlcommons/croissant/pull/448 fixes it. If there is more work to do here, let me know and I can pick it up.
the rename to `mlcroissant` seems to be done as well.

**Comment by marcenacp** [comment]
Yes, I confirm this feature is implemented and working.

@nssalian I see https://github.com/mlcommons/croissant/issues/565 is another `good first issue`. WDYT?
