### ISSUE TITLE
Clean up representation of identifiers and references

### ISSUE THREAD

**Issue by benjelloun** [mlcommons/croissant#115]
In this [discussion](https://github.com/mlcommons/croissant/discussions/51), a better representation of identifiers and references was proposed:

- Dropping the "#{}" syntax for references, since it's always clear from the context that this is a refefence.
- Splitting the container / field references into separate structured properties under "source"
- using a "selector" property to specify the selection method (e.g., csv column, json query, etc.)

This proposal need to be reflected in the spec, the examples, and supported in the validator.

**Comment by pierrot0** [comment]
Note that while such refactoring done manually is still possible today, it might be tedious.
I think we need a Croissant to Croissant converter (https://github.com/mlcommons/croissant/issues/109) to make such migrations easier. In the long run, such a converter will be a must have.

**Comment by marcenacp** [comment]
Spec: https://github.com/mlcommons/croissant/pull/143

**Comment by marcenacp** [comment]
Closing this issue, as the feature is implemented in the verifier.
