### ISSUE TITLE
when "--debug" then error due to missing pygraphviz

### ISSUE THREAD

**Issue by St3V0Bay** [mlcommons/croissant#220]
**How to reproduce?**

1. Run `python -m pip install ".[dev]"`
2. `python scripts/validate.py --file ../../datasets/titanic/metadata.json --debug`

Same command as in (2) but without `--debug` works.

![Screenshot 2023-09-18 at 22 37 59](https://github.com/mlcommons/croissant/assets/87860698/2e280475-a618-4606-b279-17179e48e14e)

**Comment by goeffthomas** [comment]
I believe @marcenacp fixed this with #243
