### ISSUE TITLE
Converter script can output a valid JSON-LD for ibm-nasa-geospatial/hls_burn_scars.

### ISSUE THREAD

**Issue by marcenacp** [mlcommons/croissant#231]
Link: https://huggingface.co/datasets/ibm-nasa-geospatial/hls_burn_scars

**Comment by marcenacp** [comment]
@xhagrg @omshinde I could successfully generate the Croissant file with:

```bash
python scripts/from_huggingface_to_croissant.py --dataset ibm-nasa-geospatial/hls_burn_scars --output /tmp/json-ld.json
```

However, when generating this dataset (`python scripts/load.py --file /tmp/json-ld.json --record_set=default`), I still have an error:

```
  ...
  File "/usr/local/google/home/pierremarcenac/Documents/mlcommons/croissant/python/mlcroissant/mlcroissant/_src/operation_graph/operations/field.py", line 29, in _cast_value
    return deps.PIL_Image.open(io.BytesIO(value))
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f38038690d0>
```

**Comment by marcenacp** [comment]
Opening the parquet file with Hugging Face gives the same error, so it's likely that the generated parquet files are corrupted.

**Comment by marcenacp** [comment]
So, in this case, we cannot rely on HF infrastructure. We're better off writing the whole Croissant file manually:

```json
{
  "@context": {
    "@language": "en",
    "@vocab": "https://schema.org/",
    "column": "ml:column",
    "data": {
      "@id": "ml:data",
      "@type": "@json"
    },
    "dataType": {
      "@id": "ml:dataType",
      "@type": "@vocab"
    },
    "extract": "ml:extract",
    "field": "ml:field",
    "fileProperty": "ml:fileProperty",
    "format": "ml:format",
    "includes": "ml:includes",
    "isEnumeration": "ml:isEnumeration",
    "jsonPath": "ml:jsonPath",
    "ml": "http://mlcommons.org/schema/",
    "parentField": "ml:parentField",
    "path": "ml:path",
    "recordSet": "ml:recordSet",
    "references": "ml:references",
    "regex": "ml:regex",
    "repeated": "ml:repeated",
    "replace": "ml:replace",
    "sc": "https://schema.org/",
    "separator": "ml:separator",
    "source": "ml:source",
    "subField": "ml:subField",
    "transform": "ml:transform"
  },
  "@type": "sc:Dataset",
  "name": "hls_burn_scars",
  "description": "This dataset contains Harmonized Landsat and Sentinel-2 imagery of burn scars and the associated masks for the years 2018-2021 over the contiguous United States. There are 804 512x512 scenes. Its primary purpose is for training geospatial machine learning models.\n",
  "citation": "@software{HLS_Foundation_2023,\n    author = {Phillips, Christopher and Roy, Sujit and Ankur, Kumar and Ramachandran, Rahul},\n    doi    = {10.57967/hf/0956},\n    month  = aug,\n    title  = {{HLS Foundation Burnscars Dataset}},\n    url    = {https://huggingface.co/ibm-nasa-geospatial/hls_burn_scars},\n    year   = {2023}\n}\n",
  "license": "cc-by-4.0",
  "url": "https://huggingface.co/datasets/ibm-nasa-geospatial/hls_burn_scars",
  "distribution": [
    {
      "@type": "sc:FileObject",
      "name": "tar-gz",
      "description": "Source *.tar.gz containing all the data.",
      "contentUrl": "https://huggingface.co/datasets/ibm-nasa-geospatial/hls_burn_scars/resolve/main/hls_burn_scars.tar.gz",
      "encodingFormat": "application/x-tar",
      "sha256": "4e6f99a75cb2c500547b20662a15cbd531dc421376f815e91846ea542798e8e6"
    },
    {
      "@type": "sc:FileSet",
      "name": "source-images",
      "containedIn": "tar-gz",
      "encodingFormat": "image/tiff",
      "includes": "*/*._merged.tif"
    },
    {
      "@type": "sc:FileSet",
      "name": "source-annotations",
      "containedIn": "tar-gz",
      "encodingFormat": "image/tiff",
      "includes": "*/*.mask.tif"
    }
  ],
  "recordSet": [
    {
      "@type": "ml:RecordSet",
      "name": "images",
      "description": "The images.",
      "field": [
        {
          "@type": "ml:Field",
          "name": "id",
          "description": "Unique ID.",
          "dataType": "sc:Text",
          "source": {
            "distribution": "source-images",
            "extract": {
              "fileProperty": "filename"
            },
            "transform": {
              "regex": "^(\\*)\\._merged\\.tif$"
            }
          }
        },
        {
          "@type": "ml:Field",
          "name": "content",
          "description": "Each tiff file contains a 512x512 pixel tiff file. Scenes contain six bands, and masks have one band. For satellite scenes, each band has already been converted to reflectance.",
          "dataType": "sc:ImageObject",
          "source": {
            "distribution": "source-images",
            "extract": {
              "fileProperty": "content"
            }
          }
        },
        {
          "@type": "ml:Field",
          "name": "split",
          "description": "The split the data belongs to (either `training` or `validation`). The 804 files have been randomly split into training (2/3) and validation (1/3) directories, each containing the masks, scenes, and index files.",
          "dataType": "sc:Text",
          "source": {
            "distribution": "source-images",
            "extract": {
              "fileProperty": "fullpath"
            },
            "transform": {
              "regex": "^(training|validation)\\/\\*\\.tiff$"
            }
          }
        }
      ]
    },
    {
      "@type": "ml:RecordSet",
      "name": "annotations",
      "description": "The annotations.",
      "field": [
        {
          "@type": "ml:Field",
          "name": "id",
          "description": "Unique ID.",
          "dataType": "sc:Text",
          "source": {
            "field": "source-annotations",
            "extract": {
              "fileProperty": "filename"
            },
            "transform": {
              "regex": "^(\\*)\\.mask\\.tif$"
            }
          }
        },
        {
          "@type": "ml:Field",
          "name": "content",
          "description": "Masks are a single band with values: 1 = Burn scar 0 = Not burned -1 = Missing data.",
          "dataType": "sc:ImageObject",
          "source": {
            "distribution": "source-annotations",
            "extract": {
              "fileProperty": "content"
            }
          }
        }
      ]
    },
    {
      "@type": "ml:RecordSet",
      "name": "images_with_annotations",
      "description": "The images with the annotations.",
      "field": [
        {
          "@type": "ml:Field",
          "name": "split",
          "description": "See images/split.",
          "dataType": "sc:Text",
          "source": {
            "field": "images/split"
          }
        },
        {
          "@type": "ml:Field",
          "name": "id",
          "description": "Unique ID.",
          "dataType": "sc:Text",
          "references": {
            "field": "annotations/id"
          },
          "source": {
            "field": "images/id"
          }
        },
        {
          "@type": "ml:Field",
          "name": "image",
          "description": "See images/content.",
          "dataType": "sc:ImageObject",
          "source": {
            "field": "images/content"
          }
        },
        {
          "@type": "ml:Field",
          "name": "annotation",
          "description": "See annotations/content.",
          "dataType": "sc:ImageObject",
          "source": {
            "field": "annotations/content"
          }
        }
      ]
    }
  ]
}
```

However, there is still a problem when loading this file,  because there is a brand new case where we have to "chain" multiple RecordSets. I can try to implement this and add the dataset to the integration tests.

**Comment by omshinde** [comment]
Thank you @marcenacp ..Really appreciate it. Will it be possible for us to tag along in this development? Please let us know. Both of us, @xhagrg and I are interested. 

> However, there is still a problem when loading this file, because there is a brand new case where we have to "chain" multiple RecordSets. I can try to implement this and add the dataset to the integration tests.

Am I correct to interpret "chaining" as "nesting" of files? Also, if a json-ld file is laded correctly, can we directly use it for training or access the dataset from it. Just trying to understand the workflow.

**Comment by marcenacp** [comment]
> Am I correct to interpret "chaining" as "nesting" of files?

It's the first example of an ml:RecordSet consuming another ml:RecordSet. This is what I meant with "chain".

It's still a WIP, but PR https://github.com/mlcommons/croissant/pull/244 should allow consuming the JSON-LD for `ibm-nasa-geospatial/hls_burn_scars`

**Comment by omshinde** [comment]
Thanks for the update @marcenacp ..Appreciate it.. We will report back to you with confirmation.
cc: @xhagrg

**Comment by marcenacp** [comment]
@omshinde @xhagrg Do you have any news?

After consideration, I think option #1 (https://github.com/mlcommons/croissant/issues/231#issuecomment-1764773876) is better in the long term, because Hugging Face doesn't auto convert to Parquet big datasets.

**Comment by omshinde** [comment]
Thanks @marcenacp .. I am getting following message while executing the script - 

```
(base) rajatshinde@shinde23-mbp mlcroissant % python scripts/from_huggingface_to_croissant.py --dataset ibm-nasa-geospatial/hls_burn_scars --output /tmp/json-ld.json
Traceback (most recent call last):
  File "/Users/rajatshinde/impact/croissant/python/mlcroissant/mlcroissant/scripts/from_huggingface_to_croissant.py", line 193, in <module>
    app.run(main)
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/anaconda3/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/rajatshinde/impact/croissant/python/mlcroissant/mlcroissant/scripts/from_huggingface_to_croissant.py", line 185, in main
    jsonld = convert(dataset)
  File "/Users/rajatshinde/impact/croissant/python/mlcroissant/mlcroissant/scripts/from_huggingface_to_croissant.py", line 147, in convert
    encoding_format=mlc.EncodingFormat.GIT,
AttributeError: module 'mlcroissant' has no attribute 'EncodingFormat'
```

Python version - `3.10.9`
OS - MacOS

Steps - 
1. Cloned the `mlcroissant` repo
2. Run installation using `python -m pip install ".[dev]" `
3. Executed `python scripts/from_huggingface_to_croissant.py --dataset ibm-nasa-geospatial/hls_burn_scars --output /tmp/json-ld.json`

Am I missing something here?

**Comment by marcenacp** [comment]
You should use the JSON-LD from https://github.com/mlcommons/croissant/issues/231#issuecomment-1764773876.

- Copy the JSON to `/tmp/hls_burn_scars.json`.
- Run the generation in Python with:

```bash
import mlcroissant as mlc
dataset = mlc.Dataset("/tmp/hls_burn_scars.json", debug=True)
records = dataset.records("images_with_annotations")
print(next(iter(records)))
```

The last step will return the first record which is a dict with:

```json
{
  "image": "... very long bytes with the image ...", 
  "split": b"training",
  "id": b"subsetted_512x512_HLS.S30.T10SDH.2020248.v1.4",
  "annotation": <PIL.TiffImagePlugin.TiffImageFile image mode=I size=512x512 at 0x7F0256311B40>
}
```

(PS: However I will investigate the error you encountered with `scripts/from_huggingface_to_croissant.py`.)

**Comment by marcenacp** [comment]
> Am I missing something here?

As far as the Hugging Face script is concerned, you need to be in the Python project (= at the same level as the pyproject.toml).

- `git clone ...`
- `cd croissant/python/mlcroissant` (and not `cd croissant/python/mlcroissant/mlcroissant`)
- `python mlcroissant/scripts/from_huggingface_to_croissant.py --dataset ...`

PR https://github.com/mlcommons/croissant/pull/283 will simplify this by having a CLI that you can call from the command line.

**Comment by omshinde** [comment]
>The last step will return the first record which is a dict with:
{
    "image": "... very long bytes with the image ...", 
    "split": b"training",
    "id": b"subsetted_512x512_HLS.S30.T10SDH.2020248.v1.4",
    "annotation": <PIL.TiffImagePlugin.TiffImageFile image mode=I size=512x512 at 0x7F0256311B40>
  }
  If it's useful to you, you can create a PR with the dataset. Maybe you want to add some more metadata.

I'am able to generate this, there was some issue with `pygraphviz` in my local setup. Thank you @marcenacp 

>PR https://github.com/mlcommons/croissant/pull/283 will simplify this by having a CLI that you can call from the command line. Please, tell me if it fixes your issue.

Great. Thanks for this too.

So, I confirm that this script is working, although we will have to wait till we get it working for the HF datasets as most of our datasets will be hosted there. We would try to perform some experiments for our other datasets and post the updates here.

**Comment by marcenacp** [comment]
> till we get it working for the HF datasets as most of our datasets will be hosted there. We would try to perform some experiments for our other datasets and post the updates here.

The script `scripts/from_huggingface_to_croissant.py` works when Hugging Face successfully auto-generated the Parquet files for the dataset. If it's not the case (as for ibm-nasa-geospatial/hls_burn_scars), the JSON-LD must be manually crafted. That's what I did in https://github.com/mlcommons/croissant/issues/231#issuecomment-1764773876. It may also be the case for the other datasets.

**Comment by omshinde** [comment]
Got it, thank you.

**Comment by marcenacp** [comment]
Closing this issue as it's now resolved!
