### ISSUE TITLE
Content fetched via HTTP doesn't support authentication

### ISSUE THREAD

**Issue by goeffthomas** [mlcommons/croissant#233]
Looking at the [_download_from_http](https://github.com/mlcommons/croissant/blob/66808bb925075045088e12fd08b91df63b71aa32/python/mlcroissant/mlcroissant/_src/operation_graph/operations/download.py#L128-L140) method, there isn’t currently any support for attaching credentials; however, the Git support that was added does include an [insert_credentials method](https://github.com/mlcommons/croissant/blob/66808bb925075045088e12fd08b91df63b71aa32/python/mlcroissant/mlcroissant/_src/operation_graph/operations/download.py#L65-L90). So a pattern does exist for reading values from the environment and adding them to the download request. Here’s how this could come together:
- Add some code to [_download_from_http](https://github.com/mlcommons/croissant/blob/66808bb925075045088e12fd08b91df63b71aa32/python/mlcroissant/mlcroissant/_src/operation_graph/operations/download.py#L128-L140) that looks for new environment variables to provide in the request. For example, `CROISSANT_BASIC_AUTH_USERNAME` and `CROISSANT_BASIC_AUTH_PASSWORD`. If those values are present, include them in the `requests.get()` as `auth=(CROISSANT_BASIC_AUTH_USERNAME, CROISSANT_BASIC_AUTH_PASSWORD)`. If the values aren’t present, make the request with the assumption that authentication isn’t needed.
- Provide instructions in the `README` for how to load a dataset that requires authentication to access `distribution.contentUrl`s. Kaggle can be used as an example since our Croissant files will necessitate pulling content via our API:
  - Provide a link for how to generate an API key on Kaggle
  - Use that API key as the `CROISSANT_BASIC_AUTH_PASSWORD`
  - Use the Kaggle username for `CROISSANT_BASIC_AUTH_USERNAME`
- Add unit tests to ensure the credentials are being added to `requests.get()` appropriately, like the ones [here](https://github.com/mlcommons/croissant/blob/66808bb925075045088e12fd08b91df63b71aa32/python/mlcroissant/mlcroissant/_src/operation_graph/operations/download_test.py#L44)

Alternatively, the [Dataset class](https://github.com/mlcommons/croissant/blob/66808bb925075045088e12fd08b91df63b71aa32/python/mlcroissant/mlcroissant/_src/datasets.py#L40C12-L40C12) could include an arg for credentials. Long-term, this may be a better UX for someone loading datasets from a variety of platforms, each with their own auth. That way users wouldn't have to change environment variables in between each `Dataset` use. The `Dataset` itself would allow the creds to be "bundled" into it. Since the Git credentials are environment-based already, I'd think migrating both to this new "bundled" approach would maybe be better done together to avoid diverging approaches to auth.

**Comment by goeffthomas** [comment]
@marcenacp Because this is a blocker to having functional Croissant files from Kaggle, I'm planning to do this work. Please LMK your thoughts on the changes I've suggested.

**Comment by marcenacp** [comment]
@goeffthomas, thanks for looking into this! The option with the environment variables LGTM.

I think passing the password as an argument is a viable option if the default remains the environment variable. Otherwise, it makes the code uncommitable in version control without leaking the password.

I still see an issue at this stage. Users may need to make various HTTP calls to different providers with different username/passwords. How would we account for this? In addition to the environment variables that you describe, we could have ad hoc environment variables like `CROISSANT_BASIC_AUTH_PASSWORD_${name of the FileObject}`. I think we can solve this issue later and go with the first solution you proposed for now - especially if it blocks you. WDYT?

(Also, on another note: the downloader should be customizable (e.g., a company with specific downloaders should be able to plug them). We can still natively support the most common methods like basic authentication, proxies, etc.)

**Comment by goeffthomas** [comment]
> Otherwise, it makes the code uncommitable in version control without leaking the password.

Do you mean if someone wants to share code that uses this library? I don't think it's unreasonable to expect users to safeguard their secrets appropriately. So they can/should either use a secret manager to prevent leakage or they can have managed environment variables in their code that they reference when passing to this library.

> Users may need to make various HTTP calls to different providers with different username/passwords.

That's an interesting scenario. Do we see that being an actual use case? I'd probably wait for demand before putting in that thought/work. But what you propose could maybe do the job. So basically you can set name-targeted env variables to overwrite whatever basic auth is already set when making calls for that file 👍 

> Also, on another note: the downloader should be customizable (e.g., a company with specific downloaders should be able to plug them)

Oh, so like we'd define some interface for a `Downloader` that they can pass in when creating a `Dataset`?

**Comment by goeffthomas** [comment]
@marcenacp 

> Users may need to make various HTTP calls to different providers with different username/passwords.

Thinking a bit more on this, I'm struggling to understand why this would ever happen. The `Metadata` specifies `url` as a mandatory property. That seems to indicate that the data is all colocated with one provider/site/repo. Why would the `distribution` then have `contentUrl`s that require this flexibility?

**Comment by marcenacp** [comment]
> the data is all colocated with one provider/site/repo

I think that's a very valid assumption, thank you for articulating it. Let's just focus on single credentials for now.

> a `Downloader` that they can pass in when creating a `Dataset`?

Exactly. This was more of a side note. That may later be a strong requirement for the adoption by companies.

**Comment by goeffthomas** [comment]
@marcenacp I have a branch ready to fix this, but I'm unable to push the branch to origin. Is this because I'm not listed as a contributor on the repo?
