### ISSUE TITLE
Specifying a `FileObject.containedIn` with a `contentUrl` of a relative path doesn't work

### ISSUE THREAD

**Issue by goeffthomas** [mlcommons/croissant#234]
There's an example in the repo [here](https://github.com/mlcommons/croissant/blob/5eba0378b8fa810d7deea940995d76ba8657aa8c/datasets/movielens/metadata.json#L50C17-L50C17) which leads me to believe that `contentUrl` can be a relative path from the source `FileObject` that it's `containedIn`.

But when I try to build a similar one for a Kaggle dataset, I get:
```
  File "/usr/local/google/home/goeff/py3/lib/python3.11/site-packages/mlcroissant/_src/operation_graph/operations/download.py", line 175, in __call__
    filepath = get_download_filepath(self.node, self.url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/goeff/py3/lib/python3.11/site-packages/mlcroissant/_src/operation_graph/operations/download.py", line 49, in get_download_filepath
    assert url.startswith("data/"), (
AssertionError: Local file "{self.node.uid}" should point to a file within the data/ folder next to the JSON-LD Croissant file. But got: "{self.url}"
```

For reference, I have an archive that has many files, some of which are CSVs. To build the `RecordSet`s and `Field`s, it seems like I have to target by `source.distribution`. So I'm trying to add one `FileObject` for each CSV to the top-level `distribution`s.

**Comment by marcenacp** [comment]
@goeffthomas, I opened https://github.com/mlcommons/croissant/pull/241 to implement this. Notably, you'll find a JSON-LD recipe with a working example of a CSV within a ZIP file. Does this solve your issue?

Thanks!

**Comment by goeffthomas** [comment]
> @goeffthomas, I opened #241 to implement this. Notably, you'll find a JSON-LD recipe with a working example of a CSV within a ZIP file. Does this solve your issue?
> 
> Thanks!

Yes, this looks like what I was expecting, thank you! I'll try it out next week on the examples I've been generating.
