### ISSUE TITLE
Group semantics regression on FLORES 200

### ISSUE THREAD

**Issue by mkuchnik** [mlcommons/croissant#295]
FLORES 200 was working on 0c66893 but it is different on main (487ec5cf3c3327371ae1cfd489d67acaf5ed73f1).

Repro from recipes directory:
```python3
import mlcroissant as mlc
dataset = mlc.Dataset(file="../../../datasets/flores-200/metadata.json", debug=False)
print(dataset)
records = dataset.records(record_set="language_translations_train_data_with_metadata")
print(sum(1 for r in records))
```

Before the test set was added (causing the record_set to be renamed), the call would be:
```python3
import mlcroissant as mlc
dataset = mlc.Dataset(file="../../../datasets/flores-200/metadata.json", debug=False)
print(dataset)
records = dataset.records(record_set="language_translations_with_metadata")
print(sum(1 for r in records))
```

Note: this can block for a long time in the correct case, so it may be better to print iteratively to see if count goes over 997.

The length should be 204 * 997, but it is only 997. This is because the data from each of the 204 `.dev` files have been collapsed at some point. Instead of each of the files yielding 997 rows, the effect is 997 samples and some of the columns are None.

**Comment by marcenacp** [comment]
@mkuchnik Thanks for opening the bug. I expected https://github.com/mlcommons/croissant/blob/main/datasets/recipes/output/translations_from_zip.jsonl to cover this test case (extract the filename for each line), but apparently there is a difference. I can come up with a better implementation for tomorrow.

**Comment by marcenacp** [comment]
@mkuchnik Do you confirm that PR https://github.com/mlcommons/croissant/pull/309 fixes this issue?

**Comment by mkuchnik** [comment]
@marcenacp Looks good to me! Seems a bit faster, too.
