### ISSUE TITLE
size of .git >200MB

### ISSUE THREAD

**Issue by luisoala** [mlcommons/croissant#402]
is it necessary to have .git be this large?

![Screenshot from 2023-11-28 15-13-11](https://github.com/mlcommons/croissant/assets/26168435/ac6f668c-be33-4415-9591-105ccd1817fd)

![Screenshot from 2023-11-28 15-12-53](https://github.com/mlcommons/croissant/assets/26168435/a4d4be43-3962-434b-9e7a-1a1ea879ef43)

**Comment by mkuchnik** [comment]
This seems fixable.

I used the script from https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history to rank the history. This gives:

```bash
...
04e7c452e50c  1.7MiB editor/components/tree/frontend/build/static/js/main.5a572f5d.js.map
6b5b61ede90d  1.9MiB editor/components/tabs/frontend/build/static/js/main.a44b10fc.js.map
51f017c6898c  1.9MiB editor/components/tabs/frontend/build/static/js/main.e6b754d8.js.map
8fac424284aa  2.5MiB CC_BY_SA_formatted.jsonl
f4ad12057595   18MiB datasets/mini_CC_BY_SA/data/0-hz-immersion-into-wallbient/04.0 Hz - Balcony Wall.mp3
769dd58f2b32   21MiB datasets/mini_CC_BY_SA/data/0-hz-immersion-into-wallbient/01.0 Hz - Entrance Wall.mp3
d8ca0d7262b3   22MiB mini_CC_BY_SA/CC_BY_SA/0-0-rainy-day-dub-september-5th-2006.zip
7f27136725fe   23MiB datasets/mini_CC_BY_SA/data/0-0-rainy-day-dub-september-5th-2006/0=0_-_Rainy_Day_Dub_September_5th_2006.mp3
4dd986758948   23MiB datasets/mini_CC_BY_SA/data/0-hz-immersion-into-wallbient/02.0 Hz - Bright Hall Wall.mp3
4f5812dc0868   28MiB datasets/mini_CC_BY_SA/data/0-hz-immersion-into-wallbient/03.0 Hz - Living Room Wall.mp3
1110658dfb85   81MiB mini_CC_BY_SA/CC_BY_SA/0-hz-immersion-into-wallbient.zip
```

We can see that most of these are audio files. We can plot the top cumulative sizes in bytes (only top 10 shown):
<img width="1070" alt="filename_vs_size" src="https://github.com/mlcommons/croissant/assets/12423239/13f170f2-31d9-40ba-b055-521d94155d8b">

We can similarly convert the cumulative sum to a percentage by normalizing by total size to approximate the removal of largest N files. Note this is a crude approximation of total size and the actual size after removal.
<img width="987" alt="filename_vs_percentage" src="https://github.com/mlcommons/croissant/assets/12423239/7f4c2f94-b8b8-4bf4-8aa6-ce2d3120a6a6">

So removing 7 files would account for over 80% of the Git log's size. It seems a lot were introduced in development of #322 
(e.g., https://github.com/mlcommons/croissant/pull/322/commits/506bd0df16d2037d6fd760cb19c7919a8be9792b) but ultimately removed.

@monke6942021 @marcenacp Should we rebase these files out?

**Comment by luisoala** [comment]
thx for the analysis michael! i just did a clone of the current version and this appears to be fixed now, correct?
