### ISSUE TITLE
Release constraints on `name`

### ISSUE THREAD

**Issue by marcenacp** [mlcommons/croissant#449]
Names are IDs with specific constraints (no white space, no special character). These constraints should be lowered except for basic checks (e.g., no line return?).

**Comment by goeffthomas** [comment]
@marcenacp Curious about the name length requirement as well. Is that a hard requirement of one of our dependencies? Curious if other data providers have expressed similar concerns.

**Comment by marcenacp** [comment]
Notes on offline conversations we had with Pierre, Omar and Stanze:

- Name of dataset: no constraint (not even on length).
- Name of RecordSet/Field/etc: https://www.w3.org/TR/xml/#sec-common-syn. Names are supposed to be IDs, so by convention we should use `@id` (standard in JSON-LD). Currently we picked the CSVW standard.
