### ISSUE TITLE
[CI] Flaky Editor End-to-End Tests 

### ISSUE THREAD

**Issue by mkuchnik** [mlcommons/croissant#452]
The Editor End-to-End Tests have a timer of 10000ms, or 10 seconds, which seems to occasionally fail. I force-push to re-run the CI and it will sometimes pass. An example of a failing CI is [here](https://github.com/mlcommons/croissant/actions/runs/7586293709/job/20664115861?pr=444).

```
  1) Editor loads a local CSV as a resource
       should display the form: Overview, Metadata, Resources, & Record Sets:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'This is a nice custom description!' within the element: <td#glide-cell-2-1> but never did.
      at Context.eval (webpack:///./cypress/e2e/uploadCsv.cy.js:65:45)
```

I then force-push and it passes [here](https://github.com/mlcommons/croissant/actions/runs/7586445265/job/20664617831?pr=444). Note that this patch does not touch the editor, so it's unlikely to have changed the behavior of the test.

**Comment by marcenacp** [comment]
Web end-to-end tests are often flaky. I just sent https://github.com/mlcommons/croissant/pull/462/commits/d0489f82641e90711c707003b2ae77fbdac52341 as a (very) temporary fix. We'll spend some time on the end-to-end tests this quarter :)
