### ISSUE TITLE
Generation errors in `bigcode-the-stack`, `coco2014-mini` and `simple-dataset`

### ISSUE THREAD

**Issue by marcenacp** [mlcommons/croissant#501]
Reported by @St3V0Bay

**Comment by marcenacp** [comment]
`simple-dataset`: to be removed as unused

**Comment by ccl-core** [comment]
`simple-dataset` and `bigcode-the-stack` shouldn't create more problems now.

For `coco2014-mini`, #510 proposes an ad-hoc fix, but if time allows, it would make sense to have something less hacky in place before the launch.
