### ISSUE TITLE
RAI fields in mlcroissant

### ISSUE THREAD

**Issue by marcenacp** [mlcommons/croissant#597]
It seems there's a discrepancy between the [RAI specs](https://github.com/mlcommons/croissant/blob/main/docs/croissant-rai-spec.md#rai-property-information) and [their implementation in mlcroissant](https://github.com/mlcommons/croissant/blob/a1a413cf1fb376ecc3bc4d3d6d7858f4f2b3bc61/python/mlcroissant/mlcroissant/_src/structure_graph/nodes/metadata.py#L160-L274).

@JoanGi Could you please have a look at the differences (as you initially implemented the RAI fields in mlcroissant)? Thanks!

**Comment by JoanGi** [comment]
Yes!, we already detected it when implementing the datasets with RAI fields. It is being handled in this PR https://github.com/mlcommons/croissant/pull/581

**Comment by marcenacp** [comment]
Great! Just commented on the PR.

**Comment by benjelloun** [comment]
Closing this issue. Please re-open if needed.
