### ISSUE TITLE
in spec, link to Appendix 1 is broken

### ISSUE THREAD

**Issue by pdurbin** [mlcommons/croissant#616]
Here's a visual:

![Screenshot 2024-03-20 at 4 32 02 PM](https://github.com/mlcommons/croissant/assets/21006/e62dd812-2452-4185-a294-e14d4ae9cf23)

I'm not sure how to fix this. It looks the same as the Typing RecordSets link, which works fine:

<img width="1180" alt="Screenshot 2024-03-20 at 4 33 50 PM" src="https://github.com/mlcommons/croissant/assets/21006/633a12b1-2f7e-488c-aef0-26374e4afbcc">

See also https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown

🤷

**Comment by benjelloun** [comment]
This was fixed by @dominik-kuhn  in https://github.com/mlcommons/croissant/pull/603.
