### ISSUE TITLE
FileSet extends sc:Intangible (according to documentation) but is subclass of sc:CreativeWork (according to .ttl)

### ISSUE THREAD

**Issue by doigl** [mlcommons/croissant#633]
According to the specification (/docs/croissant-spec.md, Line 702), FileSet extends sc:Intangible, but according to the ontology-file (docs/croissant.ttl, Line 16) it is a subclass of sc:CreativeWork.

```
croissant:FileSet a rdf:Class ;
  rdfs:label "FileSet" ;
  rdfs:comment "A set of homogeneous files extracted from a container, optionally filtered by inclusion and/or exclusion filters." ;
  rdfs:subClassOf schema:CreativeWork .
```
Which definition is the right one?

**Comment by Zack-83** [comment]
It seems that the specification is right and that the ontology file is going to be corrected: https://github.com/mlcommons/croissant/pull/634/files .

I don't understand why, indeed.

**Comment by benjelloun** [comment]
This is fixed now
