### ISSUE TITLE
clarify that citeAs can be used for dataset citations

### ISSUE THREAD

**Issue by pdurbin** [mlcommons/croissant#638]
In a 2024-03-20 Crossaint Task Force meeting I asked about how "citeAs" is described in the spec:

"A citation for a publication that describes the dataset."

@benjelloun explained that we are very welcome to put citations into "citeAs" that are not publications/articles/papers.

That's great but can we please clarify the spec? Here is a suggestion:

"A citation for a publication that describes the dataset or a citation to the dataset itself."

I'm still working on an implementation in bibtex but in this fake example, note that we use `@data` instead of `@article` as the example in the spec shows: `"citeAs": "@data{FK2/6ZUDGC_2024,author = {Durbin, Philip},publisher = {Root},title = {Cars},year = {2024},url = {https://doi.org/10.5072/FK2/6ZUDGC}}"` This is because in systems like Dataverse, a dataset has first-class status as a citable, scholarly object.

**Comment by benjelloun** [comment]
Thanks Phil! I will send out a PR shortly with a few fixes to the spec, including this one.
