### ISSUE TITLE
404 url:http://mlcommons.org/croissant/source

### ISSUE THREAD

**Issue by louisxavier123** [mlcommons/croissant#659]
url 404
http://mlcommons.org/croissant/source

**Comment by marcenacp** [comment]
Hi @louisxavier123, thanks for your message!

For now the whole documentation is [here for the Croissant specs](https://mlcommons.github.io/croissant/docs/croissant-spec.html) and [here for the `mlcroissant` documentation](https://mlcommons.github.io/croissant/docs/mlcroissant/Metadata.html). The goal would be to host it on mlcommons.org soon (similarly to what schema.org does). Please, tell me if it's ok for you.
