### ISSUE TITLE
[NeurIPS] Croissant for Binary Blob Data

### ISSUE THREAD

**Issue by 5had3z** [mlcommons/croissant#674]
Hi,

I have a dataset which is a custom binary format that is derived from another dataset. Each sample in this dataset can be correlated back to the original set by the filename and hash id of the sample. It's not entirely clear to me how to properly use croissant for this dataset, I have just linked it to a zip file that is hosted on a university archive to download my transformed data. The dataset doesn't really fit the typical plain-text webscraping, image captioning, tabular, or object detection etc that it seems this framework is designed for.

If I've misinterpreted anything or there is a more proper way of doing things, I'd like your feedback.

https://github.com/5had3z/sc2-serializer

Footnote: I just added the croissant.json in the repo, but didn't mention in the paper, I link the repo and data in the paper.

**Comment by benjelloun** [comment]
I'm not able to download the zip file linked from the Croissant file. The download from the server is extremely slow. Any chance you could post just a sample of your data files?

It this is a custom file format, then you are right that Croissant will not be able to read contents from it into RecordSets / Fields, out of the box, as it would for CSV or image directories.

That said, you can access the filename via extract -> fileProperty : filename, and the content line-by-line via with fileProperty: lines, and then you can run regular expressions on both the filename and the contents of your data files to extract the fields for your recordset definition.

See for example [Flores-200](https://github.com/mlcommons/croissant/blob/0f95e04763557929e4f4c6711c108c0d9cf7b818/datasets/1.0/flores-200/metadata.json)

Hope this helps,
Omar

**Comment by 5had3z** [comment]
Here is a link to the page that hosts the data (rather than the direct download) https://bridges.monash.edu/articles/dataset/Tournament_Starcraft_II/25865566. If you download it is probably best to grab one that's >100MB (smaller ones might be empty).

This is like a proprietary database, you can't read the line-by-line, its all scambled and compressed. You can use my reader and transform a replay into a big tensor of properties, but again, that needs my reader and post-hoc transforms on data structs to do that. I have an sqlite database that contains metadata about the replays included, but you're not really meant to use that for learning on or anything, just filtering and checking some general distribution properties about the replay data like game duration, player factions etc.

**Comment by benjelloun** [comment]
Got it. Croissant will not be able to address the contents of the proprietary format, so all you can do is to define FileObject and FileSet like you already did (unless you are willing to convert the data to a more standard format like CSV). You can still specify dataset-level metadata of course.

Best,
Omar

**Comment by 5had3z** [comment]
Thanks, I just wanted to make sure I wasn't missing anything that would result in a desk reject or something. Maybe a plugin framework could be implemented that defines a custom data reader that is auto pip-installed and used for datasets like mine.

Not having >100TB worth of CSV to read is the point of this dataset formatting :smile:.
